name: Feature
description: A change you want in Aeko
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: what
    attributes:
      label: What should Aeko do
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why it matters
    validations:
      required: false
